In [4]:
mylist = [1,2,3]
print(mylist)

[1, 2, 3]


In [5]:
import numpy as np
arr = np.array(mylist)
print(arr)

[1 2 3]


In [53]:
arr

array([1, 2, 3])

In [42]:
mymat = [[1,2,3],[4,5,6],[7,8,9]]



In [43]:
matrix = np.array(mymat)

In [44]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
np.zeros(5) #We will get a vector out

array([0., 0., 0., 0., 0.])

In [47]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [48]:
np.zeros((5,5)) #representing as (rows, columns)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.ones((5,5)) #representing as (rows, columns)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
np.zeros((2,3)) #Two rows AND Three cols

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.linspace(0,5,10) #Cretes 10 evenly space points from 0-5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [52]:
np.linspace(0,5,5) #5 evenly spaces from 0-5

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [55]:
np.eye(4) #This will show 1.s in diagonal and rest all zeros in 4*4 matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
np.eye(120)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [61]:
np.random.rand(5) #5 random distributions from 0-1    1 DIMENTIONAL

array([0.2794332 , 0.60358848, 0.92338142, 0.99912539, 0.5044999 ])

In [64]:
np.random.rand(5,5) # 5*5 random distributions from 0-1    2 DIMENTIONAL

array([[0.66145272, 0.00365659, 0.02791271, 0.16351831, 0.19055149],
       [0.55210694, 0.39500883, 0.46078428, 0.29767261, 0.8878715 ],
       [0.86468745, 0.19642495, 0.39060891, 0.1732014 , 0.61077062],
       [0.60423312, 0.80385554, 0.76992623, 0.27473846, 0.35881237],
       [0.80583454, 0.10483308, 0.58178957, 0.94482345, 0.39379097]])

In [71]:
np.random.randn(4) #Not only from 0-1. 1 DIMENTIONAL

array([-1.79980295, -0.80314826, -0.51345963,  2.00055001])

In [73]:
np.random.randn(4,4) #Not only from 0-1. 2 DIMENTIONAL

array([[ 2.88216705, -1.18367802, -1.97625249,  1.55253439],
       [-0.85926968,  0.75883025,  0.35671473,  0.09672706],
       [-1.0404213 , -1.19516586,  1.4719736 , -0.48927436],
       [-0.35546511,  1.06248499,  0.89492551,  0.6691722 ]])

In [81]:
np.random.randint(5) #This will random integers from random low to high integer. hERE FROM 0-5

2

In [88]:
np.random.randint(9,30293) #Random integer from 9-30293 this time

array([24395,  1730, 16546, 12913, 29826, 20073,  6658,  8337,  1825])

In [100]:
np.random.randint(4,10,10) # Represents (low,high,no of digits for output)

array([6, 9, 5, 7, 6, 8, 8, 6, 6, 4])

# Revision

In [101]:
arr = np.arange(24)

In [ ]:
arr

In [107]:
ranarr = np.random.randint(0,50,10)

In [105]:
ranarr

array([21, 36, 11,  2, 46, 41, 37, 21, 14, 25])

# Reshape MEATHOD
## This is used for reshaping an array into dimentions

In [123]:
arr = np.arange(25)
arr.reshape(5,5) # arr is defined above. reshaping 1D to 2D array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [164]:
new = np.random.randint(1,101,100)
new.reshape(10,10)

array([[54, 47, 93, 84, 13,  1, 47, 74, 27, 89],
       [28, 44, 20, 10,  2, 38, 14, 48, 64, 39],
       [67, 97, 99, 33, 49, 38, 71, 20, 67, 41],
       [60, 88, 98, 25, 68, 40, 12, 65, 45, 38],
       [32, 92, 54, 90, 99, 98, 94, 58, 79, 99],
       [ 2, 35,  6, 79, 47, 28, 55,  9, 18, 54],
       [59, 32, 95, 69, 47, 95,  2, 98, 34, 83],
       [54, 44,  7, 63, 18, 23, 48, 18,  7, 43],
       [36, 40, 84, 27, 98, 19, 69, 16, 22,  6],
       [92, 42, 79, 15, 34, 64, 58, 25,  5, 54]])

In [160]:
arr = np.random.randint(0,25,25)
arr.reshape(5,5)


array([[16, 19,  1, 23,  8],
       [22,  2,  1, 17,  3],
       [ 0, 18, 19,  1, 19],
       [12, 24, 24, 20,  0],
       [ 8, 19, 19,  7, 18]])

In [159]:
matrix = np.random.randint(0,10,9)
matrix.reshape(3,3)

array([[7, 6, 2],
       [5, 2, 1],
       [3, 1, 8]])

# MAX OR MIN VALUE

In [ ]:
arr.max()

In [3]:
mylist = [1,2,3]

In [4]:
print(mylist)

[1, 2, 3]


In [5]:
import numpy as nm
arr = nm.arr(mylist)
pr

NameError: name 'mylist' is not defined